name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release
  VCPKG_DEFAULT_TRIPLET: x64-windows

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: MSVC environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Cache vcpkg
        uses: actions/cache@v4
        with:
          path: |
            ${{ runner.temp }}/vcpkg
            ${{ runner.temp }}/vcpkg_installed
          key: vcpkg-${{ runner.os }}-${{ env.VCPKG_DEFAULT_TRIPLET }}

      - name: Setup vcpkg
        shell: pwsh
        run: |
          if (!(Test-Path "$env:RUNNER_TEMP/vcpkg")) {
            git clone --depth 1 https://github.com/microsoft/vcpkg "$env:RUNNER_TEMP/vcpkg"
            & "$env:RUNNER_TEMP/vcpkg/bootstrap-vcpkg.bat"
          }

          & "$env:RUNNER_TEMP/vcpkg/vcpkg.exe" install sdl2 sdl2-image glew --triplet $env:VCPKG_DEFAULT_TRIPLET

      - name: Cache ASTC encoder
        uses: actions/cache@v4
        with:
          path: libs/astc
          key: astc-lib-${{ runner.os }}

      - name: Build ASTC encoder (if missing)
        shell: pwsh
        run: |
          if (!(Test-Path "libs/astc/astcenc-native-static.lib")) {

            git clone --depth 1 --branch 4.x https://github.com/ARM-software/astc-encoder "$env:RUNNER_TEMP/astc-encoder"

            cmake -S "$env:RUNNER_TEMP/astc-encoder" -B "$env:RUNNER_TEMP/astc-encoder/build" -A x64
            cmake --build "$env:RUNNER_TEMP/astc-encoder/build" --config Release --parallel

            $lib = Get-ChildItem "$env:RUNNER_TEMP/astc-encoder/build" -Recurse -Filter "astcenc-native-static.lib" | Select-Object -First 1

            if (-not $lib) {
              $lib = Get-ChildItem "$env:RUNNER_TEMP/astc-encoder/build" -Recurse -Filter "*astcenc*static*.lib" | Select-Object -First 1
            }

            if (-not $lib) {
              throw "ASTC static lib not found"
            }

            New-Item -ItemType Directory -Force -Path "libs/astc" | Out-Null
            Copy-Item $lib.FullName "libs/astc/astcenc-native-static.lib" -Force

            Write-Host "Copied ASTC lib"
          }
          else {
            Write-Host "Using cached ASTC library"
          }

      - name: Configure CMake
        shell: pwsh
        run: |
          cmake -S . -B build -A x64 `
            -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} `
            -DCMAKE_TOOLCHAIN_FILE="$env:RUNNER_TEMP/vcpkg/scripts/buildsystems/vcpkg.cmake"

      - name: Build
        shell: pwsh
        run: |
          cmake --build build --config ${{ env.BUILD_TYPE }} --parallel
